export const skillsData = [
        {
            data:[{
            skillName:"HTML",
            percentage:"90",
            }
            ]
        },
        {
            data:[{
                skillName:"CSS",
            percentage:"70",
            }]
            
        },
        {
            data:[{
            skillName:"JAVASCRIPT",
            percentage:"80",
            }]
        },
        {
            data:[{
            skillName:"REACTJS",
            percentage:"60",
            }]
        },
        {
            data:[{
            skillName:"CPP",
            percentage:"90",
            }]
        },
        {
            data:[{
            skillName:"DSA",
            percentage:"80",
            }]
        },
        {
            data:[{
            skillName:"MYSQL",
            percentage:"70",
            }]
        },
        {
            data:[{
            skillName:"Java",
            percentage:"70",
            }]
        },
]